"""
SQLAlchemy models for archaeological data
These mirror the PyArchInit database schema (Supabase version)
"""
from sqlalchemy import Column, Integer, BigInteger, String, Text, Float, Numeric, DateTime, JSON
from sqlalchemy.orm import relationship
from ..database import Base


class Site(Base):
    """Archaeological site"""
    __tablename__ = 'site_table'

    id_sito = Column(BigInteger, primary_key=True)
    sito = Column(Text)
    nazione = Column(String(255))
    regione = Column(String(255))
    comune = Column(String(255))
    descrizione = Column(Text)
    provincia = Column(String(255))
    definizione_sito = Column(String(255))
    sito_path = Column(Text)
    find_check = Column(BigInteger)


class US(Base):
    """Stratigraphic Unit"""
    __tablename__ = 'us_table'

    id_us = Column(BigInteger, primary_key=True)
    sito = Column(Text)
    area = Column(Text)
    us = Column(Text)
    d_stratigrafica = Column(String(255))
    d_interpretativa = Column(String(255))
    descrizione = Column(Text)
    interpretazione = Column(Text)
    periodo_iniziale = Column(String(255))
    fase_iniziale = Column(String(255))
    periodo_finale = Column(String(255))
    fase_finale = Column(String(255))
    scavato = Column(String(255))
    attivita = Column(String(255))
    anno_scavo = Column(String(255))
    metodo_di_scavo = Column(String(255))
    inclusi = Column(Text)
    campioni = Column(Text)
    rapporti = Column(Text)
    data_schedatura = Column(String(255))
    schedatore = Column(String(255))
    formazione = Column(String(255))
    stato_di_conservazione = Column(String(255))
    colore = Column(String(255))
    consistenza = Column(String(255))
    struttura = Column(String(255))
    cont_per = Column(String(255))
    order_layer = Column(BigInteger)
    documentazione = Column(Text)
    unita_tipo = Column(String(255))
    settore = Column(Text)
    quad_par = Column(Text)
    ambient = Column(Text)
    saggio = Column(Text)
    elem_datanti = Column(Text)
    funz_statica = Column(Text)
    lavorazione = Column(Text)
    spess_giunti = Column(Text)
    letti_posa = Column(Text)
    alt_mod = Column(Text)
    un_ed_riass = Column(Text)
    reimp = Column(Text)
    posa_opera = Column(Text)
    quota_min_usm = Column(Numeric)
    quota_max_usm = Column(Numeric)
    cons_legante = Column(Text)
    col_legante = Column(Text)
    aggreg_legante = Column(Text)
    con_text_mat = Column(Text)
    col_materiale = Column(Text)
    inclusi_materiali_usm = Column(Text)
    n_catalogo_generale = Column(Text)
    n_catalogo_interno = Column(Text)
    n_catalogo_internazionale = Column(Text)
    soprintendenza = Column(Text)
    quota_relativa = Column(Numeric)
    quota_abs = Column(Numeric)
    ref_tm = Column(Text)
    ref_ra = Column(Text)
    ref_n = Column(Text)
    posizione = Column(Text)
    criteri_distinzione = Column(Text)
    modo_formazione = Column(Text)
    componenti_organici = Column(Text)
    componenti_inorganici = Column(Text)
    lunghezza_max = Column(Numeric)
    altezza_max = Column(Numeric)
    altezza_min = Column(Numeric)
    profondita_max = Column(Numeric)
    profondita_min = Column(Numeric)
    larghezza_media = Column(Numeric)
    quota_max_abs = Column(Numeric)
    quota_max_rel = Column(Numeric)
    quota_min_abs = Column(Numeric)
    quota_min_rel = Column(Numeric)
    osservazioni = Column(Text)
    datazione = Column(Text)
    flottazione = Column(Text)
    setacciatura = Column(Text)
    affidabilita = Column(Text)
    direttore_us = Column(Text)
    responsabile_us = Column(Text)
    cod_ente_schedatore = Column(Text)
    data_rilevazione = Column(Text)
    data_rielaborazione = Column(Text)
    lunghezza_usm = Column(Numeric)
    altezza_usm = Column(Numeric)
    spessore_usm = Column(Numeric)
    tecnica_muraria_usm = Column(Text)
    modulo_usm = Column(Text)
    campioni_malta_usm = Column(Text)
    campioni_mattone_usm = Column(Text)
    campioni_pietra_usm = Column(Text)
    provenienza_materiali_usm = Column(Text)
    criteri_distinzione_usm = Column(Text)
    uso_primario_usm = Column(Text)


class InventarioMateriali(Base):
    """Materials inventory"""
    __tablename__ = 'inventario_materiali_table'

    id_invmat = Column(BigInteger, primary_key=True)
    sito = Column(Text)
    numero_inventario = Column(BigInteger)
    tipo_reperto = Column(Text)
    criterio_schedatura = Column(Text)
    definizione = Column(Text)
    descrizione = Column(Text)
    area = Column(Text)
    us = Column(Text)
    lavato = Column(String(255))
    nr_cassa = Column(BigInteger)
    luogo_conservazione = Column(Text)
    stato_conservazione = Column(String(255))
    datazione_reperto = Column(String(255))
    elementi_reperto = Column(Text)
    misurazioni = Column(Text)
    rif_biblio = Column(Text)
    tecnologie = Column(Text)
    forme_minime = Column(BigInteger)
    forme_massime = Column(BigInteger)
    totale_frammenti = Column(BigInteger)
    corpo_ceramico = Column(String(255))
    rivestimento = Column(String(255))
    diametro_orlo = Column(Numeric)
    peso = Column(Numeric)
    tipo = Column(String(255))
    eve_orlo = Column(Numeric)
    repertato = Column(String(255))
    diagnostico = Column(String(255))
    n_reperto = Column(BigInteger)
    tipo_contenitore = Column(String(255))
    struttura = Column(String(255))


class Pottery(Base):
    """Pottery records"""
    __tablename__ = 'pottery_table'

    id_rep = Column(BigInteger, primary_key=True)
    id_number = Column(BigInteger)
    sito = Column(Text)
    area = Column(Text)
    us = Column(Text)
    box = Column(BigInteger)
    photo = Column(Text)
    drawing = Column(Text)
    anno = Column(BigInteger)
    fabric = Column(Text)
    percent = Column(Text)
    material = Column(Text)
    form = Column(Text)
    specific_form = Column(Text)
    ware = Column(Text)
    munsell = Column(Text)
    surf_trat = Column(Text)
    exdeco = Column(String(255))
    intdeco = Column(String(255))
    wheel_made = Column(String(255))
    descrip_ex_deco = Column(Text)
    descrip_in_deco = Column(Text)
    note = Column(Text)
    diametro_max = Column(Numeric)
    qty = Column(BigInteger)
    diametro_rim = Column(Numeric)
    diametro_bottom = Column(Numeric)
    diametro_height = Column(Numeric)
    diametro_preserved = Column(Numeric)
    specific_shape = Column(Text)
    bag = Column(BigInteger)
    sector = Column(Text)


class MediaThumb(Base):
    """Media thumbnails"""
    __tablename__ = 'media_thumb_table'

    id_media_thumb = Column(BigInteger, primary_key=True)
    id_media = Column(BigInteger)
    mediatype = Column(String(255))
    media_filename = Column(String(255))
    media_thumb_filename = Column(String(255))
    filetype = Column(String(255))
    filepath = Column(Text)
    path_resize = Column(Text)


class MediaToEntity(Base):
    """Media to entity associations"""
    __tablename__ = 'media_to_entity_table'

    id_mediaToEntity = Column(BigInteger, primary_key=True)
    id_entity = Column(BigInteger)
    entity_type = Column(String(255))
    table_name = Column(String(255))
    id_media = Column(BigInteger)
    filepath = Column(Text)
    media_name = Column(String(255))
